version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./google_cloud_credentials.json:/app/google_cloud_credentials.json
      - translated_documents:/app/translated_documents
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_cloud_credentials.json
    networks:
      - app-network
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    command: >
      sh -c "ollama serve & sleep 10 && ollama pull mistral:latest && tail -f /dev/null"

networks:
  app-network:
    driver: bridge

volumes:
  translated_documents:
  ollama_data: 